name: Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  scenario1:
    name: scenario11
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          pwd ; ls -lah ; curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash -s ; orca-cli -v ; orca-cli -p ${{ env.PROJECT_KEY }} -k ${{ secrets.ORCA_SECURITY_API_TOKEN }} iac scan .
